<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitea83621820a8d2f2532a5a51a27a8f6a
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Domain_Core\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Domain_Core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitea83621820a8d2f2532a5a51a27a8f6a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitea83621820a8d2f2532a5a51a27a8f6a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitea83621820a8d2f2532a5a51a27a8f6a::$classMap;

        }, null, ClassLoader::class);
    }
}
